# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainClientWindow(object):
    def setupUi(self, MainClientWindow):
        MainClientWindow.setObjectName("MainClientWindow")
        MainClientWindow.resize(756, 534)
        MainClientWindow.setMinimumSize(QtCore.QSize(756, 534))
        self.centralwidget = QtWidgets.QWidget(MainClientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_contact.setGeometry(QtCore.QRect(20, 416, 161, 25))
        self.btn_add_contact.setObjectName("btn_add_contact")
        self.btn_remove_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_contact.setGeometry(QtCore.QRect(20, 446, 161, 25))
        self.btn_remove_contact.setObjectName("btn_remove_contact")
        self.list_contacts = QtWidgets.QListView(self.centralwidget)
        self.list_contacts.setGeometry(QtCore.QRect(20, 30, 161, 381))
        self.list_contacts.setObjectName("list_contacts")
        self.text_message = QtWidgets.QTextEdit(self.centralwidget)
        self.text_message.setGeometry(QtCore.QRect(210, 400, 381, 71))
        self.text_message.setObjectName("text_message")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(602, 400, 89, 31))
        self.btn_send.setObjectName("btn_send")
        self.btn_clr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr.setGeometry(QtCore.QRect(602, 440, 89, 31))
        self.btn_clr.setObjectName("btn_clr")
        self.list_messages = QtWidgets.QListView(self.centralwidget)
        self.list_messages.setGeometry(QtCore.QRect(210, 30, 481, 331))
        self.list_messages.setObjectName("list_messages")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(22, 10, 90, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 220, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 375, 220, 20))
        self.label_3.setObjectName("label_3")
        MainClientWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainClientWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_exit = QtWidgets.QMenu(self.menubar)
        self.menu_exit.setObjectName("menu_exit")
        MainClientWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainClientWindow)
        self.statusbar.setObjectName("statusbar")
        MainClientWindow.setStatusBar(self.statusbar)
        self.menu_add_contact = QtWidgets.QAction(MainClientWindow)
        self.menu_add_contact.setObjectName("menu_add_contact")
        self.menu_remove_contact = QtWidgets.QAction(MainClientWindow)
        self.menu_remove_contact.setObjectName("menu_remove_contact")
        self.action_3 = QtWidgets.QAction(MainClientWindow)
        self.action_3.setObjectName("action_3")
        self.menu_2.addAction(self.menu_add_contact)
        self.menu_2.addAction(self.menu_remove_contact)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_exit.menuAction())

        self.retranslateUi(MainClientWindow)
        QtCore.QMetaObject.connectSlotsByName(MainClientWindow)

    def retranslateUi(self, MainClientWindow):
        _translate = QtCore.QCoreApplication.translate
        MainClientWindow.setWindowTitle(_translate("MainClientWindow", "Мессенджер"))
        self.btn_add_contact.setText(_translate("MainClientWindow", "Добавить контакт"))
        self.btn_remove_contact.setText(_translate("MainClientWindow", "Удалить контакт"))
        self.btn_send.setText(_translate("MainClientWindow", "Отправить"))
        self.btn_clr.setText(_translate("MainClientWindow", "Очистить"))
        self.label.setText(_translate("MainClientWindow", "Контакты:"))
        self.label_2.setText(_translate("MainClientWindow", "История сообщений:"))
        self.label_3.setText(_translate("MainClientWindow", "Введите новое сообщение:"))
        self.menu_2.setTitle(_translate("MainClientWindow", "Контакт"))
        self.menu_exit.setTitle(_translate("MainClientWindow", "Выход"))
        self.menu_add_contact.setText(_translate("MainClientWindow", "Добавить контакт"))
        self.menu_remove_contact.setText(_translate("MainClientWindow", "Удалить контакт"))
        self.action_3.setText(_translate("MainClientWindow", "О программе"))
